// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset.sql

package database

import (
	"context"
)

const deleteChirps = `-- name: DeleteChirps :exec
DELETE FROM chirps
`

func (q *Queries) DeleteChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteChirps)
	return err
}

const deleteRefreshTokens = `-- name: DeleteRefreshTokens :exec
DELETE FROM refresh_tokens
`

func (q *Queries) DeleteRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokens)
	return err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}
